### ISSUE TITLE
Joining from Port #1 disturbs functioning of Port #2

### ISSUE THREAD

**Issue by shubhamk008** [grainger-illinois/CTCast#49] opened 2022-10-26 19:56 UTC
While testing on the beta player
If we begin sending text through port 2 it is sent to the transcript (good)  
Someone else sending to port 2 cannot send through at the same time (good)
If we then begin sending text through port 1 the transcript refreshes and it is sent to the transcript (mostly good)
Transcripts of port 2 disappears (worse)
No longer able to see text sent through on port 2 (worse)
The text from port 1 and port 2 does not come through as captions (worse)

Fixes needed, if it is in the transcript it should come through as captions
Can text from both ports be seen in captions/transcripts simultaneously?
Could text that appears from port 2 appear in italics in parentheses or with an AD before it (the parens or AD might cause problems with being spoken)

**Comment by angrave** [comment] 2022-11-05 16:00
This seems to be a duplicate of issue #50 

* If we then begin sending text through port 1 the transcript refreshes and it is sent to the transcript (mostly good)
Transcripts of port 2 disappears (worse)
Is desired behavior of the frontend. The frontend assumes/defines the first stream as the captions

**Closed** 2022-11-05 16:23 UTC
Labels: enhancement, wontfix
